pipeline {

    parameters {
        choice (name: 'Terraform actions', choices: ['apply','destroy'], description: 'Choose your Terraform action')

    }

    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        
    }


    agent any

    stages {

        stage('Git checkout'){
            steps{
                script{
                    dir("Terraform") {
                        git url : 'https://github.com/SK-git-2026/chatbot-sk.git', branch : 'Iac-Dev-env'
                    }
                }
            }
        }
    }

    stage ('Plan'){
        steps{
            sh 'pwd; cd eks/; terraform init'
            sh 'pwd; cd eks/; terraform plan -out tfplan'
            sh 'pwd; cd eks/; terraform show -no-color tfplan > tfplan.txt'
        }
    }

    stage ('approval'){
        steps{
            script{
                    def plan = readFile 'eks/tfplan.txt'
                    input message: "Do you want to proceed with the Terraform action?",
                    parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
                }
        }
    }

    stage('Apply or Destroy'){
            when {
                expression{
                    return  params.terraformAction == 'apply' || params.terraformAction == 'destroy'
                } 
            }
            steps{
                script{
                    if (params.terraformAction == 'apply'){
                        sh 'pwd; cd eks/; terraform apply -input=false tfplan'
                    }
                    else if (params.terraformAction == 'destroy'){
                        sh 'pwd; cd eks/; terraform destroy -auto-approve'
                    }
                }
            }
        }

    }




